version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DOMAIN=localhost:3000
      - DB_ADDR=${DB_ADDR:-redis-host.example.com}
      - DB_PORT=${DB_PORT:-6379}
      - DB_PASS=${DB_PASS:-password_placeholder}
      - DB_USER=${DB_USER:-default}
    restart: unless-stopped
